config/routes.rb
BrcBikes::Application.routes.draw do
  root "posts#index"
  resources :posts do 
    resources :photos
  end
  resources :users
  get "/signin", to: "sessions#new"
  post "signin", to: "sessions#create"
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :post
  validates_presence_of :title
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title
  has_many :photos, dependent: :nullify
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

    def require_signin!
      if current_user.nil?
        flash[:error] = "You need to sign in or sign up before continuing."
        redirect_to signin_url
      end
    end
    helper_method :require_signin!

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_post
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  def new
    @photo = @post.photos.build
  end

  def create
    @photo = @post.photos.build(photo_params)
    if @photo.save
      flash[:notice] = "Photo has been added."
      redirect_to [@post, @photo]
    else
      flash[:alert] = "Photo has not been added."
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @photo.update(photo_params)
      flash[:notice] = "Photo has been updated."
      redirect_to [@post, @photo]
    else
      flash[:alert] = "Photo has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @photo.destroy
    flash[:notice] = "Photo has been deleted."
    redirect_to @post 
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :description, :image, :image_cache)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_photo
    @photo = @post.photos.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_signin!, except: [:show, :index]
  before_action :authorize_admin!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = "Post has been created."
      redirect_to @post 
    else
      flash[:alert] = "Post has not been created."
      render "new"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Post has been updated."
      redirect_to @post
    else
      flash[:alert] = "Post has not been updated."
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Post has been deleted."
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :description)
  end

  def set_post
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The post you were looking for could not be found."
    redirect_to posts_path
  end

  def authorize_admin!
    require_signin!
    unless current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to root_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.where(email: params[:signin][:email]).first

    if user && user.authenticate(params[:signin][:password])
      session[:user_id] = user.id 
      flash[:notice] = "Signed in successfully."
      redirect_to root_url
    else
      flash[:error]
      render :new
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You have signed up successfully"
      redirect_to posts_path
    else
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Profile has been updated."
      redirect_to @user 
    else
      flash[:notice] = "Profile has not been updated."
      redirect_to 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "BRC Bikes" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "BRC Bikes", root_url %></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a  href="#">Menu</a></li>
    </ul>
    <section class="top-bar-section">
      <ul class="right">
        <li class="active"><a href="#">Contact</a></li>
        <li class="has-dropdown">
          <%= link_to "Sign in", signin_path %>
          <ul class="dropdown">
        <li><%= link_to "Sign up", new_user_path %></li>
        </ul>
        </li>
      </ul>
  </nav>
<% flash.each do |key,value| %>
  <div class="flash" id="<%= key %>">
    <%= value %>
  </div>
  <% end %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_for [@post, @photo] do |f| %>
  <% if @photo.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being added:</h2>

    <ul>
      <% @photo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
    <div>
      <% if @photo.new_record? %>
        <%= f.label :image, 'Image:' %>
        <%= f.file_field(:image, accept:"image/*;capture=camera") %>
        <%= f.hidden_field :image_cache %>
       <% else %>
          <%= image_tag(@photo.image_url, width: 300, height: 300) %>
      <% end %>
  </div>
    <% if @photo.new_record? %>
      <%= f.submit 'Add Photo' %>
    <% else %>
      <%= f.submit 'Update Photo' %>
    <% end %>
  <% end %>

app/views/photos/edit.html.erb
<h2>Editing a Photo for <%= @post.title %></h2>

<%= render "form" %>

app/views/photos/new.html.erb
<h2>Add Photo</h2>
<%= render "form" %>

app/views/photos/show.html.erb
<div id="photo">
  <h2><%= @photo.title %></h2>
  <%= link_to "Edit Photo", [:edit, @post, @photo] %>
  <%= link_to "Delete Photo", [@post, @photo], method: :delete, data: {confirm: "Are you sure you want to delete this photo?"} %>
  <%= simple_format(@photo.description) %>
  <%= image_tag(@photo.image_url, width: 300, height: 300) %>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %>
      prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_field :description %>
    <%= f.submit %>
  </p>
  <% end %>

app/views/posts/edit.html.erb
<h2>Edit post</h2>
<%= render "form" %>

app/views/posts/index.html.erb
<%= link_to "New Post", new_post_path %>
<h2>Posts</h2>
<ul>
  <% @posts.each do |post| %>
  <li><%= link_to post.title, post %></li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h2>New Post</h2>
<%= render "form" %>

app/views/posts/show.html.erb
<div id="post">
<h2><%= @post.title %></h2>
<p><%= @post.description %></p>
<% @post.photos.each do |photo|%>
<p>  <%= image_tag(photo.image_url, width: 300, height: 300) %></p>
<% end %>

<span id="author">Posted by <%= @post.user.name %></span>
<%= link_to "Edit Post", edit_post_path(@post) %><br>
<%= link_to "Delete Post", post_path(@post), method: :delete, 
                          data: {confirm: "Are you sure you want to delete this post?"} %><br>
<%= link_to "Add Photo", new_post_photo_path(@post) %><br>
<ul id="photos">
  <% @post.photos.each do |photo| %>
    <li><%= link_to photo.title, [@post, photo] %></li>
  <% end %>
</ul>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
  <div id="error_explanation" >
    <h2><%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </p>
      <% if @user.new_record? %>
        <%= f.submit "Sign Up" %>
      <% else %>
        <%= f.submit "Update Profile" %>
      <% end %>
  <% end %>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>
<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h2>User Profile</h2>
<p><%= @user.name %></p>
<p><%= @user.email %></p>
<%= link_to 'Edit Profile', edit_user_path(@user) %>